#pragma once

#include "app_dirs.h"
#include "app_info.h"
#include "autostart.h"
#include "autostart_default.h"
#include "cfg_default_values.h"
#include "cfg_keys.h"
#include "file_names.h"
#include "init.h"
#include "ocr_data_utils.h"
#include "single_instance_guard.h"
#include "sound.h"
#include "taskbar.h"
#include "update_checker.h"
#include "update_checker_default.h"
#include "user_agent.h"
