
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${APP_DESCRIPTION}")

set(CPACK_PACKAGE_VERSION_MAJOR "${APP_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${APP_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${APP_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION "${APP_VERSION}")

set(CPACK_PACKAGE_VENDOR "${APP_AUTHOR}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")

if(WIN32)
    include(dist_windows_iss)
    include(dist_windows_wix)
endif()

set(CPACK_PROJECT_CONFIG_FILE
    "${CMAKE_CURRENT_LIST_DIR}/cpack_config.cmake")

include(CPack)
