
set(CPACK_DEBIAN_PACKAGE_NAME "${APP_FILE_NAME}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_VENDOR}")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "${APP_URL}")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
